# Generated by Django 4.2.6 on 2023-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=240, verbose_name='Name')),
                ('location', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('mentorEmail', models.EmailField(max_length=254)),
                ('menteeEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
