# Generated by Django 4.2.6 on 2023-11-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_addNotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content",
            field=models.TextField(default="Notification content", max_length=255),
            preserve_default=False,
        ),
    ]
