# Generated by Django 4.2.6 on 2023-11-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_addNotificationContent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="followup",
            field=models.CharField(
                choices=[("FILL_PROFILE", "Fill your user profile")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
