# Generated by Django 4.2.6 on 2023-11-29 12:20

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_addAvatarLocation2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    backend.models.Profile.validate_avatar_dimensions,
                ],
            ),
        ),
    ]
