# Generated by Django 4.2.6 on 2023-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_addAvatarLocation3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="competencies",
            field=models.ManyToManyField(to="backend.competency"),
        ),
    ]
