# Generated by Django 4.2.6 on 2023-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_addTasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentoring",
            name="objectives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mentoring",
            name="settings",
            field=models.TextField(blank=True, null=True),
        ),
    ]
