# Generated by Django 4.2.6 on 2023-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_makeSettingsOptional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="followup",
            field=models.CharField(
                choices=[
                    ("FILL_PROFILE", "Fill your user profile"),
                    ("MENTORING_REQUESTS_PAGE", "See mentoring requests"),
                    ("MENTORINGS_PAGE", "See mentoring page"),
                    ("CONNECTION_PAGE", "See connections page"),
                    ("NONE", "No followup action"),
                ],
                default="NONE",
                max_length=255,
            ),
        ),
    ]
