# Generated by Django 4.2.6 on 2023-12-03 11:17

from django.db import migrations, models


def create_data(apps, schema_editor):
    AppSettings = apps.get_model("backend", "AppSettings")
    AppSettings(
        type="APP_NAME",
        content="MentorApp",
    ).save()
    AppSettings(
        type="INDEX_CONTENT",
        content="### This is editable content of index page. You can use markdown here.",
    ).save()
    AppSettings(
        type="HOMEPAGE_CONTENT",
        content="### This is editable content of homepage. You can use markdown here.",
    ).save()
    AppSettings(
        type="ABOUT_CONTENT",
        content="### This is editable content of about. You can use markdown here.",
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0030_newFollowupl"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            (
                                "APP_NAME",
                                "Name of the application. Defaults to MentorApp",
                            ),
                            (
                                "INDEX_CONTENT",
                                "Content of the index page. You can use markdown",
                            ),
                            (
                                "HOMEPAGE_CONTENT",
                                "Content of the homepage (shown after successful login to app). You can use markdown",
                            ),
                            (
                                "ABOUT_CONTENT",
                                "Content of the about page. You can use markdown",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.RunPython(create_data),
    ]
